/**
 ******************************************************************************
 * @file     lib.c
 * @author   Auto-generated by STM32CubeIDE
 * @version  V1.0
 * @date     31/12/2022 15:36:36
 * @brief    Default under dev library file.
 ******************************************************************************
 */

#define STM32F7xx
#define STM32F767xx

/* Includes ------------------------------------------------------------------*/
#include "stm32f7xx_hal.h"

/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{

}
